#!/bin/bash

if [ ! $1 ] #Check if there is a parameter present
then
	echo "No parameters given"
	exit 2
fi

if [ ! -d $1 ] #Check if the directory exists
then
	echo "Directory doesn't exist"
	exit 2
fi

#Print the number of directories
echo "The number of directories in the given directory $1 are `find $1 -type d 2> $$ | wc -l`"

`rm $$`

#Print the number of files
echo "The number of files in the given directory $` are `find $1 -type f 2> $$ | wc -l`"

`rm $$`

#Print the number of readable files
echo "The number f readable file in the given directory $1 are `find $1 -type f -perm -u=r 2> $$ | wc -l`"

#Print the number of writable files
echo "The number of writable files in the given directory $1 are `find $1 -type f -perm -u=w 2> $$ | wc-l`"

`rm $$`

#Print the number of executable files
echo "The number of executable files in the given directory $1 are `find $1 -type f -perm -u=x 2> $$ | wc -l`"

`rm $$`